 # Makefile for project 1 
 #NGH 


all: dump generate fastsort

dump: 
	gcc -Wall -o dump dump.c
	
generate: 
	gcc -Wall -o generate generate.c

fastsort:
	gcc -Wall -o fastsort fastsort.c


clean:
	rm dump
	rm generate
	rm fastsort
